-- Create "sessions" table
CREATE TABLE "sessions" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "refresh_token" character varying NOT NULL, "expired_at" timestamptz NOT NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "sessions_refresh_token_key" to table: "sessions"
CREATE UNIQUE INDEX "sessions_refresh_token_key" ON "sessions" ("refresh_token");
