-- Create "chats" table
CREATE TABLE "chats" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "users" jsonb NOT NULL, PRIMARY KEY ("id"));
-- Create "chat_messages" table
CREATE TABLE "chat_messages" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "userid" bigint NOT NULL, "username" character varying NOT NULL, "message" character varying NOT NULL, "time" timestamptz NOT NULL, "chat_chat_message" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "chat_messages_chats_chat_message" FOREIGN KEY ("chat_chat_message") REFERENCES "chats" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
